---
title: Homelab
description: My personal homelab dashboard
theme: light
color: sky
headerStyle: clean
useEqualHeights: true
layout:
  Media:
    style: row
    columns: 4
  Gaming:
    style: row
    columns: 4
  Network:
    style: row
    columns: 4
  Bots:
    style: row
    columns: 4
